version: '3.7'
services:
  db:
    image: postgres:14.0
    networks:
      - bookmarket
    env_file: default.env
    # volumes:
    #   - ./db:/var/lib/postgresql/data:rw

  webapp:
    environment:
      DB_URL: postgresql://bookmarket:bookmarket@db:5432/bookmarket
    networks:
      - bookmarket
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80

networks:
  bookmarket:
